#!/bin/bash

command -v getarg > /dev/null || . /lib/dracut-lib.sh

if OverlayFS="$(getarg rd.overlayfs -d rd.live.overlay.overlayfs)"; then
    load_fstype overlay || Die 'OverlayFS is required but unavailable.'
    volatile=volatile
    case "${OverlayFS%%[=/,]*}" in
        0 | no | off) unset -v 'OverlayFS' ;;
        '' | 1) ovlfs_name=LiveOS_rootfs ;;
        "${OverlayFS%%,*}") ovlfs_name=${OverlayFS%%,*} ;;
        *) # devspec present
            unset -v 'volatile'
            # with source name prefix
            [ "${OverlayFS%%,*}" != "$OverlayFS" ] && ovlfs_name=${OverlayFS%%,*}
            ;;
    esac
fi

[ -z "$root" ] && root=$(getarg root=)

# support legacy syntax of passing rd.live.image and then just the base root
if getargbool 0 rd.live.image; then
    liveroot="live:$root"
fi

if [ "${root%%:*}" = "live" ]; then
    liveroot=$root
fi

[ "${liveroot%%:*}" = "live" ] || exit 0

case "$liveroot" in
    live:nfs://* | nfs://*)
        root="${root#live:}"
        rootok=1
        ;;
    live:http://* | http://*)
        root="${root#live:}"
        rootok=1
        ;;
    live:https://* | https://*)
        root="${root#live:}"
        rootok=1
        ;;
    live:ftp://* | ftp://*)
        root="${root#live:}"
        rootok=1
        ;;
    live:torrent://* | torrent://*)
        root="${root#live:}"
        rootok=1
        ;;
    live:tftp://* | tftp://*)
        root="${root#live:}"
        rootok=1
        ;;
esac

[ "$rootok" != "1" ] && exit 0

GENERATOR_DIR="$2"
[ -z "$GENERATOR_DIR" ] && exit 1

[ -d "$GENERATOR_DIR" ] || mkdir -p "$GENERATOR_DIR"

{
    echo "# Automatically generated by dracut-livenet-generator"
    echo
    echo "[Unit]"
    echo "Before=initrd-root-fs.target"
    echo "[Mount]"
    echo "Where=/sysroot"
    if [ "$OverlayFS" ]; then
        getargbool 0 rd.overlayfs.readonly -d rd.live.overlay.readonly && readonly_overlay=--readonly
        basedirs=lowerdir="${readonly_overlay:+/run/overlayfs-r:}"/run/rootfsbase
        echo What="${ovlfs_name:=LiveOS_rootfs}"
        echo Options="${volatile:+volatile,}${basedirs}",upperdir=/run/overlayfs,workdir=/run/ovlwork
        echo "Type=overlay"
        _dev=$(echo "$ovlfs_name" | sed 's,/,\\x2f,g;s, ,\\x20,g;s,-,\\x2d,g;')
    else
        echo "What=/dev/mapper/live-rw"
        ROOTFLAGS="$(getarg rootflags)" && echo "Options=${ROOTFLAGS}"
        _dev='dev-mapper-live\x2drw'
    fi
} > "$GENERATOR_DIR"/sysroot.mount

mkdir -p "$GENERATOR_DIR/$_dev.device.d"
{
    echo "# Automatically generated by dracut-livenet-generator"
    echo
    echo "[Unit]"
    echo "JobTimeoutSec=3000"
    echo "JobRunningTimeoutSec=3000"
} > "$GENERATOR_DIR/$_dev.device.d/timeout.conf"
