#!/bin/sh
# overlayfs-lib.sh: utilities for OverlayFS use

command -v getarg > /dev/null || . /lib/dracut-lib.sh
command -v set_FS_opts_w > /dev/null || . /lib/distribution-lib.sh

# Fetch non-boolean value for rd.overlay or fall back to rd.live.overlay
get_rd_overlay() {
    local rd_overlay

    rd_overlay=$(getarg rd.overlay)
    case "$rd_overlay" in
        0 | no | off | '' | 1)
            rd_overlay=$(getarg rd.live.overlay) || return 1
            warn "Kernel command line option 'rd.live.overlay' is deprecated, use 'rd.overlay' instead."
            ;;
    esac
    echo "$rd_overlay"
}

# Call with IFS=, parse_Args "$ovl_pt" | "$p_Partition"
parse_Args() {
    # shellcheck disable=SC2068
    set -- $@ # rd.overlay or rd.live.overlay.overlayfs
    IFS=' 	
'
    for _; do
        case "$1" in
            '' | btrfs | ext[432] | f2fs | xfs)
                p_ptfsType=${1:-${p_ptfsType:-ext4}}
                ;;
            subvol=?*) subvol=${1#subvol=} ;;
            subvolid=?*) subvolid=${1#subvolid=} ;;
            *[!0-9]* | 0*)
                # Anything but a positive integer:
                case "$1" in
                    *=?*)
                        ovl_pt="$(label_uuid_to_dev "${1%%:*}")"
                        strstr "$1" ":" && ovlpath=${1##*:}
                        ;;
                    *) ovlfs_name="$1" ;;
                esac
                ;;
            *)
                # any positive integer:
                sizeGiB=$1
                ;;
        esac
        shift
    done
}

# Called from overlayfs-generator.sh, dmsquash-generator.sh, & mount-overlayfs.sh
# $1 arg_str [$2 - default ovlfs_name] [$3 - variable name]
get_ovl_pt() {
    case "${1%%[=/]*}" in
        0 | no | off) eval "$3=off" ;;
        '' | 1) ovlfs_name="${2-"${ovlfs_name-os_rootfs}"}" ;;
        "${1%%,*}") ovlfs_name=${1%%,*} ;;
        *) # devspec present
            unset -v 'volatile'
            IFS=, parse_Args "$1"
            ;;
    esac
}

# Called from overlayfs-generator.sh or dmsquash-generator.sh
overlayfs_mount_generator() {
    [ "$volatile" ] || {
        ln -sf "$ovl_pt" /run/initramfs/ovl_pt
        set_FS_opts_w "$p_ptfsType" p_ptFlags
        {
            echo "# Automatically generated by dracut-overlayfs-generator"
            echo [Unit]
            echo DefaultDependencies=no
            echo After=sysinit.target
            echo Before=dracut-pre-mount.service
            echo Requires=systemd-fsck@"$(dev_unit_name "$ovl_pt")".service
            echo After=systemd-fsck@"$(dev_unit_name "$ovl_pt")".service
            echo [Mount]
            echo Where=/run/os_persist
            echo What=/run/initramfs/ovl_pt
            echo Options=defaults,noauto,"$p_ptFlags"
            echo Type="${p_ptfsType-auto}"
        } > "$GENERATOR_DIR"/run-os_persist.mount
        mkdir -p "$GENERATOR_DIR/"run-os_persist.device.d
        {
            echo [Unit]
            echo JobTimeoutSec=3000
            echo JobRunningTimeoutSec=3000
        } > "$GENERATOR_DIR"/run-os_persist.device.d/timeout.conf
    }

    {
        echo "# Automatically generated by dracut-overlayfs-generator"
        echo [Unit]
        echo DefaultDependencies=no
        echo [Mount]
        echo Where=/run/rootfsbase
        echo What=/run/initramfs/rorootfs
        echo Options=defaults,noauto,"$rflags",ro
        echo Type="${rfstype-auto}"
    } > "$GENERATOR_DIR"/run-rootfsbase.mount
    mkdir -p "$GENERATOR_DIR/"run-rootfsbase.device.d
    {
        echo [Unit]
        echo JobTimeoutSec=3000
        echo JobRunningTimeoutSec=3000
    } > "$GENERATOR_DIR"/run-rootfsbase.device.d/timeout.conf

    {
        echo "# Automatically generated by dracut-overlayfs-generator"
        echo [Unit]
        echo DefaultDependencies=no
        echo After=dracut-pre-mount.service
        echo Before=initrd-root-fs.target
        echo [Mount]
        echo Where=/sysroot
        getargbool 0 rd.overlay.readonly && readonly_overlay=--readonly
        basedirs=lowerdir="${readonly_overlay:+/run/overlayfs-r:}"/run/rootfsbase
        echo What="${ovlfs_name:=os_rootfs}"
        echo Options="${basedirs}",upperdir=/run/overlayfs,workdir=/run/ovlwork
        echo Type=overlay
    } > "$GENERATOR_DIR"/sysroot.mount
    ovlfs_name=$(echo "$ovlfs_name" | sed 's,/,\\x2f,g;s, ,\\x20,g;s,-,\\x2d,g;')

    mkdir -p "$GENERATOR_DIR/$ovlfs_name".device.d
    {
        echo [Unit]
        echo JobTimeoutSec=3000
        echo JobRunningTimeoutSec=3000
    } > "$GENERATOR_DIR/$ovlfs_name".device.d/timeout.conf
}

mount_partition() {
    [ -d "${mntDir:=/run/os_persist}" ] || mkdir -p "$mntDir"
    if [ "${DRACUT_SYSTEMD-}" ]; then
        systemctl start run-os_persist.mount || Die "Unable to mount $mntDir."
    else
        # Repurpose 99-mount-root.sh for mounting the persistence partition.
        fstype="${p_ptfsType:-auto}" srcPartition="$overlay_pt" \
            mountPoint="$mntDir" srcflags="$p_ptFlags" fsckoptions="$fsckoptions" \
            override=override . "$hookdir"/mount/99-mount-root.sh
    fi
    if findmnt "$mntDir" > /dev/null 2>&1; then
        mkdir -p "$mntDir${ovl_dir:+/"$ovl_dir"}/ovlwork" "$mntDir$ovlpath"
    else
        prompt_message \
            '   Failed to mount the persistent overlay; using a temporary one.' \
            '  All new root filesystem changes will be lost on shutdown.' \
            '  Press [Enter] to continue.'
    fi
}

do_overlayfs() {
    if [ ! "$ovlpath" ] || [ "$ovlpath" = "auto" ]; then
        ovlpath="/${ovl_dir}/overlay-$label-$uuid"
    elif ! str_starts "$ovlpath" "/"; then
        ovlpath=/"${ovlpath}"
    fi

    if [ "$ovl_pt" ] && [ "$ovlpath" ]; then
        mkdir -m 0755 -p "${mntDir:=/run/os_persist}"
        if [ "$1" ]; then
            # We need $ovl_pt writable for overlay storage
            [ ! -w "$mntDir" ] && [ ! "$readonly_overlay" ] && mount -o remount,rw "$mntDir"
        else
            [ "${DRACUT_SYSTEMD-}" ] || set_FS_opts_w "${p_ptfsType:=$(
                blkid --probe --match-tag TYPE --output value --usages filesystem "$ovl_pt"
            )}" p_ptFlags
            ln -sf "$ovl_pt" /run/initramfs/ovl_pt
            fstype="${p_ptfsType:-auto}" srcPartition="$ovl_pt" \
                mountPoint="$mntDir" srcflags="$p_ptFlags" fsckoptions="$fsckoptions" \
                mount_partition
        fi
        if findmnt "$mntDir" > /dev/null 2>&1; then
            mkdir -p "$mntDir${ovl_dir:+/"$ovl_dir"}/ovlwork" "$mntDir$ovlpath"
        else
            prompt_message \
                '   Failed to mount the persistent overlay; using a temporary one.' \
                '  All new root filesystem changes will be lost on shutdown.' \
                '  Press [Enter] to continue.'
        fi
        # Establish links needed for the OverlayFS mount.
        ln -s "$mntDir$ovlpath" /run/overlayfs${readonly_overlay:+-r}
        [ "$readonly_overlay" ] || ln -s "$mntDir$ovlpath"/../ovlwork /run/ovlwork
        setup=OverlayFS_setup
    fi

    if [ "$readonly_overlay" ]; then
        if [ "$setup" ]; then
            info "Using a temporary overlay."
        elif [ "$ovl_pt" ] && [ "$ovlpath" ]; then
            prompt_message \
                '   Unable to find a persistent overlay; using a temporary one.' \
                '  All root filesystem changes will be lost on shutdown.' \
                '  Press [Enter] to continue.'
        fi
        if [ "${OverlayFS}$rd_overlay" ] && ! [ -h /run/overlayfs-r ]; then
            prompt_message \
                '   Failed to find a persistent overlay; using a temporary one.' \
                '  All root filesystem changes will be lost on shutdown.' \
                '  Press [Enter] to continue.'
            unset -v 'readonly_overlay'
            ETC_KERNEL_CMDLINE="$ETC_KERNEL_CMDLINE rd.overlay.readonly=0"
        fi
        [ "$ETC_KERNEL_CMDLINE" ] && {
            mkdir -p /etc/kernel
            printf '%s' " $ETC_KERNEL_CMDLINE" >> /etc/kernel/cmdline
            [ "${DRACUT_SYSTEMD-}" ] && systemctl daemon-reload
        }
    fi
}
