#!/bin/sh
# overlayfs-generator

command -v getarg > /dev/null || . /lib/dracut-lib.sh

overlay_pt="$(getarg rd.overlayfs)" || exit 0
load_fstype overlay || Die 'OverlayFS is required but unavailable.'

volatile=volatile
case "${overlay_pt%%[=/]*}" in
    0 | no | off) exit 0 ;;
    '' | 1) ovlfs_name=os_rootfs ;;
    "${overlay_pt%%,*}") ovlfs_name=${overlay_pt%%,*} ;;
    *) # devspec present
        # with source name prefix
        [ "${overlay_pt%%,*}" != "$overlay_pt" ] && ovlfs_name=${overlay_pt%%,*}
        overlay_pt=${overlay_pt##*,}
        overlay_pt=${overlay_pt%%,*}
        overlay_pt=$(label_uuid_to_dev "${overlay_pt%%:*}")
        ;;
esac

[ "$root" ] || root=$(getarg root=)
case "$root" in
    ovl:LABEL=* | ovl:UUID=* | ovl:PARTUUID=* | ovl:PARTLABEL=*)
        root=ovl:$(label_uuid_to_dev "${root#ovl:}")
        rootok=1
        ;;
    ovl:/dev/*)
        rootok=1
        ;;
esac
[ "$rootok" ] || exit 0

GENERATOR_DIR="$2"
[ "$GENERATOR_DIR" ] || exit 1
[ -d "$GENERATOR_DIR" ] || mkdir -p "$GENERATOR_DIR"

rflags="$(getarg rootflags=)"
{
    echo "# Automatically generated by dracut-overlayfs-generator"
    echo [Unit]
    echo Before=sysroot.mount
    echo [Mount]
    echo Where=/run/rootfsbase
    echo What="${root#ovl:}"
    echo Options="$rflags",ro
    echo Type=auto
} > "$GENERATOR_DIR"/run-rootfsbase.mount
mkdir -p "$GENERATOR_DIR/"run-rootfsbase.device.d
{
    echo [Unit]
    echo JobTimeoutSec=3000
    echo JobRunningTimeoutSec=3000
} > "$GENERATOR_DIR"/run-rootfsbase.device.d/timeout.conf

{
    echo "# Automatically generated by dracut-overlayfs-generator"
    echo [Unit]
    echo Before=initrd-root-fs.target
    echo Requires=run-rootfsbase.mount
    echo After=run-rootfsbase.mount
    echo [Mount]
    echo Where=/sysroot
    getargbool 0 rd.overlayfs.readonly && readonly_overlay=--readonly
    basedirs=lowerdir="${readonly_overlay:+/run/overlayfs-r:}"/run/rootfsbase
    echo What="${ovlfs_name:=os_rootfs}"
    echo Options="${basedirs}",upperdir=/run/overlayfs,workdir=/run/ovlwork
    echo Type=overlay
} > "$GENERATOR_DIR"/sysroot.mount
ovlfs_name=$(echo "$ovlfs_name" | sed 's,/,\\x2f,g;s, ,\\x20,g;s,-,\\x2d,g;')

mkdir -p "$GENERATOR_DIR/$ovlfs_name".device.d
{
    echo [Unit]
    echo JobTimeoutSec=3000
    echo JobRunningTimeoutSec=3000
} > "$GENERATOR_DIR/$ovlfs_name".device.d/timeout.conf

[ "$volatile" ] || {

    p_ptFlags=$(getarg rd.ovl.flags)
    {
        echo "# Automatically generated by dracut-overlayfs-generator"
        echo [Unit]
        echo Before=sysroot.mount
        echo [Mount]
        echo Where=/run/os_persist
        echo What="$overlay_pt"
        echo Options="$p_ptFlags"
        echo Type=auto
    } > "$GENERATOR_DIR"/run-os_persist.mount
    mkdir -p "$GENERATOR_DIR/"run-os_persist.device.d
    {
        echo [Unit]
        echo JobTimeoutSec=3000
        echo JobRunningTimeoutSec=3000
    } > "$GENERATOR_DIR"/run-os_persist.device.d/timeout.conf
}
