#!/bin/sh
# overlayfs-lib.sh: utilities for OverlayFS use

command -v getarg > /dev/null || . /lib/dracut-lib.sh
command -v set_FS_opts_w > /dev/null || . /lib/distribution-lib.sh
command -v parse_cfgArgs > /dev/null || . /lib/partition-lib.sh

# Fetch non-boolean values for rd.overlay or fall back to rd.live.overlay
# $1 - ovlfs_name - OverlayFS mount source name default.
get_rd_overlay() {
    rd_dm_overlay="$(getarg rd.dm.overlay -d rd.live.overlay)" \
        && IFS=, parse_cfgArgs ovl,"$rd_dm_overlay"
    OverlayFS="$(getarg rd.live.overlay.overlayfs)" && {
        warn "Kernel command line option 'rd.live.overlay.overlayfs' is deprecated, use 'rd.overlay' instead."
        case "$OverlayFS" in
            0 | no | off) unset -v 'OverlayFS' ;;
            '' | 1)
                [ "$rd_dm_overlay" ] || {
                    # For legacy case of using dmsquash-live for an OverlayFS
                    #   on a regular block root device:
                    OverlayFS=os_rootfs
                    ovlfs_name=os_rootfs
                    warn "This use of 'rd.live.overlay.overlayfs' is deprecated, use 'root=ovl:<device_specification>' instead."
                }
                ;;
            *) ovlfs_name="$OverlayFS" ;;
        esac
        [ "$OverlayFS" ] && { load_fstype overlay || warn 'OverlayFS is requested but unavailable.'; }
    }
    : "${ovlfs_name:="${1-os_rootfs}"}"
    ln -s "$ovlfs_name" /run/initramfs/ovlfs
    volatile=volatile
    ln -s tmpfs /run/initramfs/p_pt
    rd_overlay="$(getarg rd.overlay)" && {
        # Set p_pt, p_ptfstype, size; toggle volatile.
        IFS=, parse_cfgArgs ovl,"$rd_overlay"
        OverlayFS="$ovlfs_name"
    }
    ovl_dir="$(getarg rd.ovl.dir -d rd.live.dir)"
    case "$1" in
        os_rootfs) : "${ovl_dir:=RootOvl}" ;;
        LiveOS_rootfs) : "${ovl_dir:=LiveOS}" ;;
    esac
    ln -s "$ovl_dir" /run/initramfs/ovl_dir
    [ "$OverlayFS" ] && {
        load_fstype overlay || {
            unset -v 'OverlayFS'
            etc_kernel_cmdline="$etc_kernel_cmdline rd.overlay=0"
        }
    }
    [ "$volatile" ] || set_FS_opts_w "$p_ptfsType" p_ptFlags
    getargbool 0 rd.overlay.reset -d -y rd.live.overlay.reset && {
        reset_overlay=yes
        ln -s yes /run/initramfs/reset_ovl
    }
    getargbool 0 rd.overlay.readonly -d -y rd.live.overlay.readonly && {
        readonly_overlay=--readonly
        ln -s readonly /run/initramfs/ro_ovl
    }
}

# Called from overlayfs-generator.sh or dmsquash-generator.sh
overlayfs_mount_generator() {
    [ "$volatile" ] || {
        ln -sf "$p_pt" /run/initramfs/p_pt
        set_FS_opts_w "$p_ptfsType" p_ptFlags
        {
            echo "# Automatically generated by dracut-overlayfs-generator"
            echo [Unit]
            echo DefaultDependencies=no
            echo After=sysinit.target
            echo Before=dracut-pre-mount.service
            echo Requires=systemd-fsck@"$(dev_unit_name "$p_pt")".service
            echo After=systemd-fsck@"$(dev_unit_name "$p_pt")".service
            echo [Mount]
            echo Where=/run/os_persist
            echo What=/run/initramfs/p_pt
            echo Options=defaults,noauto,"$p_ptFlags"
            echo Type="${p_ptfsType-auto}"
        } > "$GENERATOR_DIR"/run-os_persist.mount
        mkdir -p "$GENERATOR_DIR/"run-os_persist.device.d
        {
            echo [Unit]
            echo JobTimeoutSec=3000
            echo JobRunningTimeoutSec=3000
        } > "$GENERATOR_DIR"/run-os_persist.device.d/timeout.conf
    }

    {
        echo "# Automatically generated by dracut-overlayfs-generator"
        echo [Unit]
        echo DefaultDependencies=no
        echo [Mount]
        echo Where=/run/rootfsbase
        echo What=/run/initramfs/rorootfs
        echo Options=defaults,noauto,"$rflags",ro
        echo Type="${rfstype-auto}"
    } > "$GENERATOR_DIR"/run-rootfsbase.mount
    mkdir -p "$GENERATOR_DIR/"run-rootfsbase.device.d
    {
        echo [Unit]
        echo JobTimeoutSec=3000
        echo JobRunningTimeoutSec=3000
    } > "$GENERATOR_DIR"/run-rootfsbase.device.d/timeout.conf

    {
        echo "# Automatically generated by dracut-overlayfs-generator"
        echo [Unit]
        echo DefaultDependencies=no
        echo After=dracut-pre-mount.service
        echo Before=initrd-root-fs.target
        echo [Mount]
        echo Where=/sysroot
        getargbool 0 rd.overlay.readonly && {
            readonly_overlay=--readonly
            volatile=volatile
        }
        basedirs=lowerdir="${readonly_overlay:+/run/overlayfs-r:}"/run/rootfsbase
        echo What="${ovlfs_name:=os_rootfs}"
        echo Options="${volatile:+volatile,}${basedirs}",upperdir=/run/overlayfs,workdir=/run/ovlwork
        echo Type=overlay
    } > "$GENERATOR_DIR"/sysroot.mount
    ovlfs_name=$(echo "$ovlfs_name" | sed 's,/,\\x2f,g;s, ,\\x20,g;s,-,\\x2d,g;')

    mkdir -p "$GENERATOR_DIR/$ovlfs_name".device.d
    {
        echo [Unit]
        echo JobTimeoutSec=3000
        echo JobRunningTimeoutSec=3000
    } > "$GENERATOR_DIR/$ovlfs_name".device.d/timeout.conf
}

mount_partition() {
    mkdir -p "$mountPoint"
    if [ "${DRACUT_SYSTEMD-}" ]; then
        systemctl start "$(dev_unit_name "$mountPoint")".mount \
            || Die "Unable to mount $mountPoint."
    else
        # Repurpose 99-mount-root.sh for mounting the partition.
        fstype="${fstype:-auto}" srcPartition="$srcPartition" \
            mountPoint="$mountPoint" srcflags="$srcflags" fsckoptions="$fsckoptions" \
            override=override . "$hookdir"/mount/99-mount-root.sh
    fi
}

get_ovlpath() {
    ovlpath="$(readlink /run/initramfs/ovlpath)"
    [ "$ovlpath" = auto ] && unset -v 'ovlpath'
    : "${ovlpath:=/"$ovl_dir"/overlay-"$label"-"$uuid"}"
    str_starts "$ovlpath" '/' || ovlpath=/"$ovlpath"
}

do_overlayfs() {
    get_ovlpath
    if [ "$p_pt" ] && [ "$ovlpath" ]; then
        mkdir -m 0755 -p "${mntDir:=/run/os_persist}"
        if [ "$1" ]; then
            # We need $p_pt writable for overlay storage
            [ ! -w "$mntDir" ] && [ ! "$readonly_overlay" ] && mount -o remount,rw "$mntDir"
        else
            [ "${DRACUT_SYSTEMD-}" ] || set_FS_opts_w "${p_ptfsType:=$(det_fs "$p_pt")}" p_ptFlags
            ln -sf "$p_pt" /run/initramfs/p_pt
            fstype="${p_ptfsType:-auto}" srcPartition="$p_pt" \
                mountPoint="$mntDir" srcflags="$p_ptFlags" fsckoptions="$fsckoptions" \
                mount_partition
        fi
        if findmnt "$mntDir" > /dev/null 2>&1; then
            mkdir -p "$mntDir${ovl_dir:+/"$ovl_dir"}/ovlwork" "$mntDir$ovlpath"
        else
            prompt_message \
                '   Failed to mount the persistent overlay; using a temporary one.' \
                '  All new root filesystem changes will be lost on shutdown.' \
                '  Press [Enter] to continue.'
        fi
        # Establish links needed for the OverlayFS mount.
        ln -s "$mntDir$ovlpath" /run/overlayfs${readonly_overlay:+-r}
        [ "$readonly_overlay" ] || ln -s "$mntDir$ovlpath"/../ovlwork /run/ovlwork
        setup=OverlayFS_setup
    fi

    if [ "$readonly_overlay" ]; then
        if [ "$setup" ]; then
            info "Using a temporary overlay."
        elif [ "$p_pt" ] && [ "$ovlpath" ]; then
            prompt_message \
                '   Unable to find a persistent overlay; using a temporary one.' \
                '  All root filesystem changes will be lost on shutdown.' \
                '  Press [Enter] to continue.'
        fi
        if [ "${OverlayFS}$rd_overlay" ] && ! [ -h /run/overlayfs-r ]; then
            prompt_message \
                '   Failed to find a persistent overlay; using a temporary one.' \
                '  All root filesystem changes will be lost on shutdown.' \
                '  Press [Enter] to continue.'
            unset -v 'readonly_overlay'
            ETC_KERNEL_CMDLINE="$ETC_KERNEL_CMDLINE rd.overlay.readonly=0"
        fi
        [ "$ETC_KERNEL_CMDLINE" ] && {
            mkdir -p /etc/kernel
            printf '%s' " $ETC_KERNEL_CMDLINE" >> /etc/kernel/cmdline
            [ "${DRACUT_SYSTEMD-}" ] && systemctl daemon-reload
        }
    fi
}
