#!/bin/sh
# dmsquash-generator

command -v getarg > /dev/null || . /lib/dracut-lib.sh

if OverlayFS="$(getarg rd.overlay -d -y rd.live.overlay.overlayfs)"; then
    load_fstype overlay || Die 'OverlayFS is required but unavailable.'
    command -v get_ovl_pt > /dev/null || . /lib/overlayfs-lib.sh

    # For legacy case of using dmsquash-live for an OverlayFS on a regular
    #   block root device:
    case "${OverlayFS%%[=/]*}" in
        '' | 1) OverlayFS=os_rootfs ;;
    esac
    ovlfs_name=os_rootfs
    get_ovl_pt "$OverlayFS" LiveOS_rootfs OverlayFS
    [ "$OverlayFS" = off ] && unset -v 'OverlayFS'
fi

[ -z "$root" ] && root=$(getarg root=)

# support legacy syntax of passing rd.live.image and then just the base root
if getargbool 0 rd.live.image; then
    liveroot="live:$root"
fi

if [ "${root%%:*}" = "live" ]; then
    liveroot=$root
fi

[ "${liveroot%%:*}" = "live" ] || exit 0

case "$liveroot" in
    live:LABEL=* | LABEL=* | live:UUID=* | UUID=* | live:PARTUUID=* | PARTUUID=* | live:PARTLABEL=* | PARTLABEL=*)
        root="live:$(label_uuid_to_dev "${root#live:}")"
        rootok=1
        ;;
    live:CDLABEL=* | CDLABEL=*)
        root="${root#live:}"
        root="$(echo "$root" | sed 's,/,\\x2f,g;s, ,\\x20,g')"
        root="live:/dev/disk/by-label/${root#CDLABEL=}"
        rootok=1
        ;;
    live:/*.[Ii][Ss][Oo] | /*.[Ii][Ss][Oo])
        root="${root#live:}"
        root="liveiso:${root}"
        rootok=1
        ;;
    live:/dev/*)
        rootok=1
        ;;
    live:/*.[Ii][Mm][Gg] | /*.[Ii][Mm][Gg])
        [ -f "${root#live:}" ] && rootok=1
        ;;
esac
getarg live.updates= && {
    case "$liveroot" in
        live:nfs://* | nfs://*)
            root="${root#live:}"
            rootok=1
            ;;
        live:http://* | http://*)
            root="${root#live:}"
            rootok=1
            ;;
        live:https://* | https://*)
            root="${root#live:}"
            rootok=1
            ;;
        live:ftp://* | ftp://*)
            root="${root#live:}"
            rootok=1
            ;;
        live:torrent://* | torrent://*)
            root="${root#live:}"
            rootok=1
            ;;
        live:tftp://* | tftp://*)
            root="${root#live:}"
            rootok=1
            ;;
    esac
}
[ "$rootok" ] || exit 0

GENERATOR_DIR="$2"
[ -z "$GENERATOR_DIR" ] && exit 1
[ -d "$GENERATOR_DIR" ] || mkdir -p "$GENERATOR_DIR"

rfstype="$(getarg rootfstype=)"
rflags="$(getarg rootflags=)"

if [ "$OverlayFS" ]; then
    overlayfs_mount_generator
else
    {
        echo "# Automatically generated by dracut-dmsquash-generator"
        echo
        echo [Unit]
        echo DefaultDependencies=no
        echo Before=initrd-root-fs.target
        echo [Mount]
        echo Where=/sysroot
        echo What=/dev/mapper/live-rw
        echo Options="${rflags}"
        echo Type="${rfstype-auto}"
    } > "$GENERATOR_DIR"/sysroot.mount

    mkdir -p "$GENERATOR_DIR"/dev-mapper-live\x2drw.device.d
    {
        echo "# Automatically generated by dracut-dmsquash-generator"
        echo
        echo [Unit]
        echo JobTimeoutSec=3000
        echo JobRunningTimeoutSec=3000
    } > "$GENERATOR_DIR/"dev-mapper-live\x2drw.device.d/timeout.conf
fi
